function Heatmap() {
  this.name = 'American Football Quarterback Heatmap: 2014';
  this.id = 'heatmap';
  this.loaded = false;

  // Preload the data - NOTE: SIMULATED DATA, DATA WAS GENERATED BY ME. 
    // HEATMAP-DATA.CSV DOES NOT REPRESENT ACTUAL NFL QB HEATMAP
    // ONLY USED FOR VISUALISATION PURPOSES
  this.preload = function() {
    var self = this;
    this.data = loadTable(
      './data/heatmap/heatmap-data.csv', 'csv', 'header',
      function(table) {
        self.loaded = true;
      }
    );
  };

  // Setup the heatmap visualization
  this.setup = function() {
    if (!this.loaded) {
      return;
    }

    // Create a dropdown select menu for months (Jan, Feb, Mar, etc.)
    this.selectMonth = createSelect();
    this.selectMonth.position(305, 60);

    // Populate dropdown with column names except the first one ("Category")
    var columns = this.data.columns.slice(1);
    for (var i = 0; i < columns.length; i++) {
      this.selectMonth.option(columns[i]);
    }

    // Event listener for the month dropdown selection
    this.selectMonth.changed(() => this.draw());
  };

  // Cleanup any DOM elements or variables when switching visualizations
  this.destroy = function() {
    if (this.selectMonth) {
      this.selectMonth.remove();
    }
  };

  // Draw the heatmap
  this.draw = function() {
    if (!this.loaded) {
      console.log('Heatmap data not yet loaded');
      return;
    }
    
    // Clear the canvas
    clear();
    background(255);

    var selectedMonth = this.selectMonth.value();
    if (selectedMonth) {
      this.drawHeatmap(selectedMonth);
    }
  };

// Function to draw the heatmap based on the selected month
  this.drawHeatmap = function(monthName) {
    // Get the "Category" column and the selected month's data
    var categories = this.data.getColumn('Category');
    var columnData = this.data.getColumn(monthName).map(Number);  // Convert to numbers
    var minValue = min(columnData);
    var maxValue = max(columnData);

    // Set up the grid dimensions
    var numCategories = categories.length;
    var cellWidth = width / numCategories;
    var cellHeight = height - 100; // Leave space for header and padding

    for (var i = 0; i < numCategories; i++) {
      var value = columnData[i];
      
      // Map the value to a color gradient between blue and red
      var cellColor = map(value, minValue, maxValue, 0, 1);
      var r = lerp(0, 255, cellColor);
      var b = lerp(255, 0, cellColor);
      
      fill(r, 0, b);
      noStroke();
      var x = i * cellWidth;
      var y = 50;  // Start below the header
      
      rect(x, y, cellWidth, cellHeight);
      
      // Add category labels
      fill(0);
      textSize(14);
      textAlign(CENTER, CENTER);
      text(categories[i], x + cellWidth / 2, y + cellHeight / 2 - 20);

      // Add value labels
      fill(255);
      textSize(18);
      text(value, x + cellWidth / 2, y + cellHeight / 2 + 20);
    }

    // Draw title
    fill(0);
    noStroke();
    textSize(24);
    textAlign(CENTER, CENTER);
    text(monthName + ' Heatmap', width / 2, 30);
  };
}